export type UseCasePage = {
  slug: string;
  title: string;
  description: string;
  targetToolSlug: string;
  intent: string;
};

export const useCasePages: UseCasePage[] = [
  {
    slug: 'compress-image-to-20kb',
    title: 'Compress Image to 20KB Online Free',
    description: 'Reduce JPG, PNG, or WebP images to around 20KB for forms and uploads without major quality loss.',
    targetToolSlug: 'compress-image',
    intent: 'compress image to 20kb',
  },
  {
    slug: 'compress-image-to-50kb',
    title: 'Compress Image to 50KB Online',
    description: 'Quickly optimize image file size to 50KB for portals, job forms, and exam applications.',
    targetToolSlug: 'compress-image',
    intent: 'compress image to 50kb',
  },
  {
    slug: 'compress-image-to-100kb',
    title: 'Compress Image to 100KB Without Losing Quality',
    description: 'Resize and optimize images to 100KB for online uploads while preserving readability and clarity.',
    targetToolSlug: 'compress-image',
    intent: 'compress image to 100kb',
  },
  {
    slug: 'resize-image-for-passport',
    title: 'Resize Image for Passport Photo',
    description: 'Create passport-size photos in the correct dimensions (2x2 inch, 35x45 mm, and more).',
    targetToolSlug: 'passport-size-photo',
    intent: 'resize image for passport photo',
  },
  {
    slug: 'resize-image-for-instagram',
    title: 'Resize Image for Instagram Post and Story',
    description: 'Set exact Instagram dimensions for feed, story, and reel covers in one click.',
    targetToolSlug: 'resize-image',
    intent: 'resize image for instagram',
  },
  {
    slug: 'convert-heic-to-jpg-online',
    title: 'Convert HEIC to JPG Online',
    description: 'Turn iPhone HEIC photos into JPG for universal compatibility on all devices.',
    targetToolSlug: 'heic-to-jpg',
    intent: 'convert heic to jpg online',
  },
  {
    slug: 'png-to-jpg-converter',
    title: 'PNG to JPG Converter Online',
    description: 'Convert PNG files to JPG quickly with adjustable quality for web and email.',
    targetToolSlug: 'png-to-jpeg',
    intent: 'png to jpg converter',
  },
  {
    slug: 'merge-pdf-files-online-free',
    title: 'Merge PDF Files Online Free',
    description: 'Combine multiple PDF files into one document without sign-up or watermark.',
    targetToolSlug: 'merge-pdf',
    intent: 'merge pdf files online free',
  },
  {
    slug: 'split-pdf-pages-online',
    title: 'Split PDF Pages Online',
    description: 'Extract specific pages or split full PDF files into smaller documents instantly.',
    targetToolSlug: 'split-pdf',
    intent: 'split pdf pages online',
  },
  {
    slug: 'compress-pdf-for-email',
    title: 'Compress PDF for Email Attachment',
    description: 'Reduce PDF size for Gmail, Outlook, and portal upload limits without losing readability.',
    targetToolSlug: 'compress-pdf',
    intent: 'compress pdf for email',
  },
  {
    slug: 'remove-background-from-image',
    title: 'Remove Background from Image Online',
    description: 'Use AI to remove photo backgrounds and export transparent PNG in seconds.',
    targetToolSlug: 'remove-image-background',
    intent: 'remove background from image',
  },
  {
    slug: 'convert-pdf-to-jpg',
    title: 'Convert PDF to JPG Online',
    description: 'Convert PDF pages into high-quality JPG images for sharing and editing.',
    targetToolSlug: 'pdf-to-jpg',
    intent: 'convert pdf to jpg',
  },
  {
    slug: 'compress-pdf-to-300kb',
    title: 'Compress PDF to 300KB Online',
    description: 'Reduce PDF file size to 300KB or less without losing document quality.',
    targetToolSlug: 'compress-pdf',
    intent: 'compress pdf to 300kb',
  },
  {
    slug: 'compress-pdf-to-100kb',
    title: 'Compress PDF to 100KB Online Free',
    description: 'Compress large PDF files down to 100KB for easy uploading and emailing.',
    targetToolSlug: 'compress-pdf',
    intent: 'compress pdf to 100kb',
  },
  {
    slug: 'compress-image-to-200kb',
    title: 'Compress Image to 200KB Online',
    description: 'Easily compress JPEG and PNG images to 200KB while maintaining clarity.',
    targetToolSlug: 'compress-image',
    intent: 'compress image to 200kb',
  },
  {
    slug: 'resize-image-to-kb',
    title: 'Resize Image to Specific KB',
    description: 'Resize and compress your image to an exact KB size requirement.',
    targetToolSlug: 'compress-image',
    intent: 'resize image to kb',
  },
  {
    slug: 'resize-image-in-cm',
    title: 'Resize Image in CM Online',
    description: 'Easily resize your photo in centimeters for printing or documents.',
    targetToolSlug: 'resize-image',
    intent: 'resize image in cm',
  },
  {
    slug: 'convert-heic-to-jpg-windows',
    title: 'Convert HEIC to JPG on Windows',
    description: 'Convert iPhone HEIC images to JPG format directly on your Windows PC.',
    targetToolSlug: 'heic-to-jpg',
    intent: 'convert heic to jpg windows',
  },
  {
    slug: 'reduce-photo-size-for-email',
    title: 'Reduce Photo Size for Email',
    description: 'Shrink photo file sizes to attach them to emails easily without limits.',
    targetToolSlug: 'compress-image',
    intent: 'reduce photo size for email',
  },
  {
    slug: 'merge-pdf-files-windows',
    title: 'Merge PDF Files on Windows',
    description: 'Quickly merge and combine multiple PDF files on Windows without installing software.',
    targetToolSlug: 'merge-pdf',
    intent: 'merge pdf files windows',
  },
  {
    slug: 'jpg-to-pdf-converter',
    title: 'JPG to PDF Converter Online Free',
    description: 'Convert JPG, JPEG, and PNG images into a single PDF document quickly and securely.',
    targetToolSlug: 'image-to-pdf',
    intent: 'jpg to pdf converter',
  },
  {
    slug: 'jpeg-to-png-converter-online',
    title: 'JPEG to PNG Converter Online',
    description: 'Convert standard JPEG files into high-quality PNG format with transparent support.',
    targetToolSlug: 'jpeg-to-png',
    intent: 'jpeg to png converter online',
  },
  {
    slug: 'increase-image-size-to-100kb',
    title: 'Increase Image Size to 100KB',
    description: 'Easily increase your photo file size to 100KB for application and portal limits.',
    targetToolSlug: 'increase-image-size-in-kb',
    intent: 'increase image size to 100kb',
  },
  {
    slug: 'remove-image-metadata-online',
    title: 'Remove Image Metadata Online',
    description: 'Strip EXIF data, location tags, and metadata from your photos for privacy and security.',
    targetToolSlug: 'remove-image-metadata',
    intent: 'remove image metadata online',
  },
  {
    slug: 'create-passport-size-photo-free',
    title: 'Create Passport Size Photo Free',
    description: 'Crop and generate passport and visa photos matching official ID dimension requirements.',
    targetToolSlug: 'passport-size-photo',
    intent: 'create passport size photo free',
  },
];
