[phases.setup]
aptPkgs = ["ghostscript", "qpdf", "libreoffice-writer", "libreoffice-calc", "tesseract-ocr", "tesseract-ocr-eng", "fonts-liberation"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "npm start"
